version: '3.8'

services:
  fastapi:
    build: .
    command: sh -c "uvicorn app.main:app --reload --port=800 --host=0.0.0.0"
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgresql:5432/mydatabase

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./app:/src/app
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      

volumes:
  postgres_data: